### PR TITLE
Allow cancellation of image uploads

### PR DESCRIPTION
**Pull request by mikeger**
- The image messages since assets V3 does not have the preview.

### CODE REVIEW

**Comment by vytis** [comment]
Maybe some test would be useful here?

**Comment by mikeger** [comment]
@vytis OK, I would add one. 🌮

**Comment by daehn** [comment]
@mikeger @vytis We can also discuss if we need this logic here at all. At the moment it is not possible to cancel a v3 asset client message upload which represents an image, this is only possible for files. So we could also remove the context change tracker as well as adding a `ZMTaskCreationHandler` to the request.

**Comment by mikeger** [comment]
@daehn but if you think about it, cancelling the image upload can be actually useful. Also if you delete the image being uploaded, what happens?

**Comment by daehn** [comment]
@mikeger I am unsure but I don't think deleting a not yet fully send message is possible.

**Comment by mikeger** [comment]
@daehn OK, let's then create the ticket to improve this one in the future and close this PR?

**Comment by daehn** [comment]
@mikeger sounds good!

**Comment by daehn** [comment]
Created [#8515](https://wearezeta.atlassian.net/browse/ZIOS-8515).

**Pull request closed without merging**
