### PR TITLE
Update for updated data-model-api

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* Use updated `wire-ios-data-model` API.

### This PR depends on:
- [x] A new release of `wire-ios-data-model` after https://github.com/wireapp/wire-ios-data-model/pull/233 has been merged.

### CODE REVIEW

**Comment by mikeger** [comment]
🔥 Conflict

**Comment by daehn** [comment]
@mikeger fixed

**Comment by vytis** [comment]
Several tests seem to be failing...

**Comment by mikeger** [comment]
@vytis @daehn  I guess the `wire-ios-data-model` has to be bumped?

**Comment by daehn** [comment]
Yes, but first I have to create a new release of `wire-ios-request-strategy` as this has been a major `wire-ios-data-model` release.

**Comment by daehn** [comment]
@mikeger  @vytis I bumped the components, but let's wait for Circle.

**Comment by daehn** [comment]
@mikeger @vytis tests are ✅

**Pull request merged**
