### PR TITLE
Remove usage of isEncrypted

### PR DESCRIPTION
**Pull request by typfel**
## Issue

The `isEncrypted` has been removed from the `ZMMessage` class. So any usage of needs to be removed

## Notice

Since the downloading of unencrypted v2 assets did depend on the `isEncrypted ` flag a new flag has been introduced: `hasEncryptedAsset` which fulfils the same purpose but it's a computed property.

## Depends on

- [x] https://github.com/wireapp/wire-ios-data-model/pull/416

### CODE REVIEW

**Comment by vytis** [comment]
Are the product/CS people aware of this change?

**Comment by typfel** [comment]
@vytis no this must be discussed of course. Or we find another way to determine if we need to request non encrypted assets (if asset id is `nil`?).

**Comment by vytis** [comment]
So maybe let's add "Do not merge" until this is settled?

**Comment by typfel** [comment]
@vytis replaced the `isEncrypted` property with a check if the message contains any encryption keys in order to restore support for downloading unencrypted V2 images.

**Pull request merged**
